sudo: required
dist: trusty
language: node_js
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - node_modules
    - bower_components
install:
  - travis_retry npm install -g bower polylint web-component-tester
  - travis_retry npm install
  - travis_retry bower install
script:
  - npm run lint
  - travis_retry xvfb-run npm test
